info:
  app:
    name: config-server
    description: My Area Guide
    version: 1.0-SNAPSHOT

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/{application}

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.show-details: always
  metrics.export.prometheus.enabled: true
  info.env.enabled: true

server:
  port: 0
  shutdown: graceful

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}${random.uuid}
    preferIpAddress: false
    hostname: localhost

logging:
  level:
    root: DEBUG
    org.springframework.cloud: TRACE
    io.grpc: DEBUG
    com.netflix: DEBUG