services:

  discovery-server:
    build: infra/discovery-server
    image: discovery-server
    container_name: discovery-server
    restart: on-failure
    ports:
      - "8761:8761"
    environment:
      - eureka.instance.hostname=discovery-server

  config-server:
    build: infra/config-server
    image: config-server
    container_name: config-server
    restart: on-failure
    ports:
      - "8181:8181"
    depends_on:
      - discovery-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.hostname=config-server
      - server.port=8181

  gateway-server:
    build: infra/gateway-server
    image: gateway-server
    container_name: gateway-server
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.hostname=gateway-server
      - server.port=8080

  user-service:
    build: core/user-service
    image: user-service
    container_name: user-service
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - db-main
      - discovery-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-main:5432/main_db?currentSchema=user_service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.hostname=user-service
      - server.port=8082

  event-service:
    build: core/event-service
    image: event-service
    container_name: event-service
    restart: on-failure
    ports:
      - "8083:8083"
    depends_on:
      - db-main
      - discovery-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-main:5432/main_db?currentSchema=event_service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.hostname=event-service
      - server.port=8083

  request-service:
    build: core/request-service
    image: request-service
    container_name: request-service
    restart: on-failure
    ports:
      - "8084:8084"
    depends_on:
      - db-main
      - discovery-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-main:5432/main_db?currentSchema=request_service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.hostname=request-service
      - server.port=8084

  comment-service:
    build: core/comment-service
    image: comment-service
    container_name: comment-service
    restart: on-failure
    ports:
      - "8085:8085"
    depends_on:
      - db-main
      - discovery-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-main:5432/main_db?currentSchema=comment_service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.hostname=comment-service
      - server.port=8085

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    restart: on-failure
    ports:
      - "8090:8090"
    depends_on:
      - db-stat
      - discovery-server
      - config-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-stat:5432/stat_db
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.hostname=stats-server
      - server.port=8090

  db-main:
    image: postgres:alpine
    container_name: db-main
    ports:
      - "5433:5432"
    volumes:
      - ./main-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  db-stat:
    image: postgres:alpine
    container_name: db-stat
    ports:
      - "5432:5432"
    volumes:
      - ./stat-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
