info:
  app:
    name: discovery-server
    description: My Area Guide
    version: 1.0-SNAPSHOT
  company:
    name: Somekind Software

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.show-details: always
  metrics.export.prometheus.enabled: true
  info.env.enabled: true

spring:
  application:
    name: discovery-server

server:
  port: 8761
  shutdown: graceful

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/