info:
  app:
    name: collector
    description: My Area Guide
    version: 1.0-SNAPSHOT

my-area-guide:
  kafka:
    user-action-topic: stats.user-actions.v1
    events-similarity-topic: stats.events-similarity.v1

server:
  shutdown: graceful

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.show-details: always
  metrics.export.prometheus.enabled: true
  info.env.enabled: true

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      value-serializer: ru.practicum.serializer.GeneralAvroSerializer
      acks: all
      retries: 10
      linger-ms: 5
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

grpc:
  server:
    port: 9099

logging:
  level:
    ru.practicum.service.UserActionService: DEBUG
    io.grpc: DEBUG
