info:
  app:
    name: analyzer
    description: My Area Guide
    version: 1.0-SNAPSHOT

my-area-guide:
  kafka:
    user-action-topic: stats.user-actions.v1
    events-similarity-topic: stats.events-similarity.v1
    user-action-consumer-group: analyzer-user-action-group-01
    events-similarity-consumer-group: analyzer-events-similarity-group-01
    bootstrap-servers: localhost:9092
    auto-offset-reset: latest
    enable-auto-commit: false
    max-poll-records: 500
  analyzer:
    weights:
      like: 1.0
      register: 0.8
      view: 0.4

server:
  shutdown: graceful

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.show-details: always
  metrics.export.prometheus.enabled: true
  info.env.enabled: true

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: create
  sql:
    init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stat_db?currentSchema=analyzer
    username: postgres
    password: 12345

grpc:
  server:
    port: 0

logging:
  level:
    ru.practicum.service.UserActionService: DEBUG
    ru.practicum.service.EventSimilarityService: DEBUG
    io.grpc: INFO