info:
  app:
    name: stats-server
    description: My Area Guide
    version: 1.0-SNAPSHOT
  company:
    name: Somekind Software

logging:
  level:
    org.springframework.web: INFO
    org.springframework.validation: INFO

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.show-details: always
  metrics.export.prometheus.enabled: true
  info.env.enabled: true

explore-with-me:
  datetime.format: yyyy-MM-dd HH:mm:ss

server:
  port: 0
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: none
  sql:
    init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stat_db
    username: postgres
    password: 12345